-- Tabla Usuarios
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Tabla Roles (ElementCollection de Users)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL
);

-- Tabla Afiliados
CREATE TABLE affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    salary DECIMAL(19, 2),
    affiliation_date DATE,
    status VARCHAR(50)
);

-- Tabla Evaluaciones de Riesgo
CREATE TABLE risk_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document VARCHAR(255),
    score INTEGER,
    risk_level VARCHAR(50),
    risk_detail VARCHAR(255),
    is_approved BOOLEAN,
    rejection_reason VARCHAR(255),
    evaluation_date TIMESTAMP
);

-- Tabla Solicitudes de Crédito
CREATE TABLE credit_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id BIGINT NOT NULL,
    requested_amount DECIMAL(19, 2),
    term_in_months INTEGER,
    proposed_rate DECIMAL(19, 2),
    application_date DATE,
    status VARCHAR(50),
    risk_evaluation_id BIGINT
);